name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install pyinstaller pyinstaller-versionfile
          $(if (Test-Path requirements.txt) { pip install -r requirements.txt })
      - name: Generate versionfile
        run: |
          create-version-file.exe versionfile.yaml --outfile versionfile
      - name: Build executable
        run: |
          pyinstaller.exe BF2AutoSpectator\spectate.py --onefile --clean --name="BF2AutoSpectator" --add-data="pickle/*.pickle;pickle/" --add-data="redist/*.exe;redist/" --version-file="versionfile"
      - name: Create release archive
        run: |
          Compress-Archive -Path "dist\BF2AutoSpectator.exe","overrides" -DestinationPath BF2AutoSpectator-${{ github.ref_name }}.zip
      - name: Create hash files
        run: |
          $(Get-FileHash -Path BF2AutoSpectator-${{ github.ref_name }}.zip -Algorithm MD5).Hash.toLower() + "`n" | Out-File -NoNewline BF2AutoSpectator-${{ github.ref_name }}.zip.md5
          $(Get-FileHash -Path BF2AutoSpectator-${{ github.ref_name }}.zip -Algorithm SHA256).Hash.toLower() + "`n" | Out-File -NoNewline BF2AutoSpectator-${{ github.ref_name }}.zip.sha256
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: BF2AutoSpectator-${{ github.ref_name }}.zip*
          draft: true
          generate_release_notes: true
          name: BF2AutoSpectator ${{ github.ref_name }}
          body: This is the ${{ github.ref_name }} release of the BF2 auto spectator.